### ISSUE TITLE
Not Working in React Native 0.67.4

### ISSUE THREAD

**Issue by sanjaymistry84** [bortolilucas/react-native-jitsimeet#22]
Jitsi button not working with version can you please resolve issue.

**Comment by bortolilucas** [comment]
@sanjaymistry84 Currently, Jitsi Meet SDK doesnt support RN >0.67. I recommend using RN 0.66

**Comment by sanjaymistry84** [comment]
I Have changed the version as per your reply but still not working all buttons 

See Below Error:
JitsiMeetSDK: [features/app] Error(TypeError){"message":"l.playTouchSound is not a function. facing this issue on clciking these buttons

Please check your end and let me know how it will resolve.


See below my packag.json

{
  "name": "myapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@bortolilucas/react-native-jitsimeet": "^2.1.1",
    "@fullcalendar/daygrid": "^5.10.1",
    "@fullcalendar/react": "^5.10.1",
    "@ptomasroos/react-native-multi-slider": "^2.2.2",
    "@react-native-async-storage/async-storage": "^1.15.9",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/progress-bar-android": "^1.0.4",
    "@react-native-community/progress-view": "^1.3.1",
    "@react-native-community/push-notification-ios": "^1.10.1",
    "@react-native-community/toolbar-android": "^0.2.1",
    "@react-native-firebase/app": "^14.2.2",
    "@react-navigation/bottom-tabs": "^6.0.5",
    "@react-navigation/drawer": "^6.1.3",
    "@react-navigation/material-top-tabs": "^5.3.19",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.1.0",
    "@react-navigation/stack": "^6.2.1",
    "@reduxjs/toolkit": "^1.7.1",
    "@twotalltotems/react-native-otp-input": "^1.3.11",
    "axios": "^0.21.1",
    "formik": "^2.2.9",
    "lodash.filter": "^4.6.0",
    "moment": "^2.29.1",
    "react": "16.13.1",
    "react-big-calendar": "^0.38.2",
    "react-data-table-component": "^7.0.2",
    "react-native": "0.66.0",
    "react-native-animatable": "^1.3.3",
    "react-native-blob-util": "^0.13.18",
    "react-native-calendar-picker": "^7.1.2",
    "react-native-camera": "^4.1.1",
    "react-native-circular-progress": "^1.3.7",
    "react-native-collapsible": "^1.6.0",
    "react-native-collapsible-tab-view": "^4.4.0",
    "react-native-date-picker": "^4.1.3",
    "react-native-dropdown-picker": "^5.1.23",
    "react-native-gesture-handler": "^2.3.2",
    "react-native-gifted-chat": "^0.16.3",
    "react-native-image-pan-zoom": "^2.1.12",
    "react-native-image-picker": "^4.0.6",
    "react-native-image-view": "^2.1.9",
    "react-native-looped-carousel": "0.1.13",
    "react-native-maps": "0.30.1",
    "react-native-maps-directions": "^1.8.0",
    "react-native-media-controls": "^2.3.0",
    "react-native-pager-view": "^5.4.1",
    "react-native-paper": "^4.9.2",
    "react-native-pdf": "^6.3.0",
    "react-native-popup-menu": "^0.15.11",
    "react-native-pose": "^0.9.1",
    "react-native-progress-bar-classic": "^1.2.1",
    "react-native-push-notification": "^8.1.1",
    "react-native-ratings": "^8.1.0",
    "react-native-razorpay": "^2.2.8",
    "react-native-reanimated": "^2.2.4",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.6.0",
    "react-native-select-multiple": "^2.1.0",
    "react-native-slider": "^0.11.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-splash-screen": "^3.3.0",
    "react-native-svg": "^12.1.1",
    "react-native-tab-view": "^2.16.0",
    "react-native-table-component": "^1.2.1",
    "react-native-tag-input": "^0.0.21",
    "react-native-textinput-material-autocomplete": "^1.0.6",
    "react-native-textinput-with-icons": "^1.0.18",
    "react-native-toast-message": "^1.4.9",
    "react-native-vector-icons": "^6.7.0",
    "react-native-video": "^5.2.0",
    "react-redux": "^7.2.2",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "rn-fetch-blob": "^0.12.0",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@babel/core": "7.12.9",
    "@babel/runtime": "7.12.5",
    "@react-native-community/eslint-config": "2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "26.6.3",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-native-codegen": "0.0.7",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by bortolilucas** [comment]
@sanjaymistry84 Have you tried this [solution](https://github.com/skrafft/react-native-jitsi-meet/issues/265#issuecomment-1065550409)?

Also, please try to use the version 2.1.2. I've bumped Jitsi Meet SDK version to 5.0.2

**Comment by riyas145** [comment]
@bortolilucas  APP CRASHED ON RELEASE BUID WHILE USING REANIMATED PLUGIN

**Comment by bortolilucas** [comment]
Have you tried matching your package versions with Jitsi Meet's? They still use version 1 of reanimated

https://github.com/jitsi/jitsi-meet/blob/master/package.json

**Comment by riyas145** [comment]
Yes I have tried that also

**Comment by bortolilucas** [comment]
Are you using hermes? Try to disable it if your using it

**Comment by sanjaymistry84** [comment]
> @sanjaymistry84 Have you tried this [solution](https://github.com/skrafft/react-native-jitsi-meet/issues/265#issuecomment-1065550409)?
> 
> Also, please try to use the version 2.1.2. I've bumped Jitsi Meet SDK version to 5.0.2

I have applied all SDK but have no luck,  the version 2.1.2 is a fire error in my environment.

**if i go thorugh JitsiMeetSDK >= 5 show the below error**
implementation ('org.jitsi.react:jitsi-meet-sdk:5.0.2') {
  transitive = true
 }


**ERROR :: Invariant Violation: requireNativeComponent: "GestureHandlerRootView" was not found in the UIManager. & Display black screen only but background camera, audio all run good.**

if i go through  JitsiMeetSDK >=3 show the below error 
 implementation ('org.jitsi.react:jitsi-meet-sdk:3.+') {
      transitive = true
    }
ERROR :: 
2022-04-05 19:42:41.388 5213-5354/com.myapp.doc E/JitsiMeetSDK: [features/app] Error(TypeError){"message":"l.playTouchSound is not a function. (In 'l.playTouchSound()', 'l.playTouchSound' is undefined)","stack":"_playTouchSound@index.android.bundle:213:9252\n_playTouchSound@[native code]\n_performSideEffectsForTransition@index.android.bundle:213:9074\n_performSideEffectsForTransition@[native code]\n_receiveSignal@index.android.bundle:213:7784\n_receiveSignal@[native code]\ntouchableHandleResponderRelease@index.android.bundle:213:5072\ntouchableHandleResponderRelease@[native code]\nb@index.android.bundle:95:1197\nk@index.android.bundle:95:1340\nC@index.android.bundle:95:1394\nN@index.android.bundle:95:1692\nA@index.android.bundle:95:2482\nforEach@[native code]\nz@index.android.bundle:95:2282\nindex.android.bundle:95:13914\n_e@index.android.bundle:95:88659\nNe@index.android.bundle:95:13582\nUe@index.android.bundle:95:13755\nreceiveTouches@index.android.bundle:95:14547\nvalue@index.android.bundle:37:3685\nindex.android.bundle:37:841\nvalue@index.android.bundle:37:2939\nvalue@index.android.bundle:37:813\nvalue@[native code]"}


See attachement
![image](https://user-images.githubusercontent.com/4919955/161773897-86a29760-1cd5-4d44-8065-1433f7f614c9.png)

**Comment by riyas145** [comment]
@bortolilucas  after disable Hermes also app get crashed when enter jitsi meet route

**Comment by riyas145** [comment]
while use same version gesturehandler 
> Task :react-native-gesture-handler:compileDebugKotlin FAILED
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    C:/Users/VC/.gradle/caches/transforms-2/files-2.1/9c68e559db00a392e0b4ea19f8419e54/jetified-kotlin-stdlib-jdk8-1.4.10.jar (version 1.4)
    C:/Users/VC/.gradle/caches/transforms-2/files-2.1/22623f9d5f46cd8b4d1d267c9600f7cf/jetified-kotlin-stdlib-jdk7-1.4.10.jar (version 1.4)
    C:/Users/VC/.gradle/caches/transforms-2/files-2.1/a884823363c73716bd0dac63b4eedb2f/jetified-kotlin-stdlib-1.5.20.jar (version 1.5)
    C:/Users/VC/.gradle/caches/transforms-2/files-2.1/f45a407b76483c0f84d1bd5dcc8521c2/jetified-kotlin-stdlib-common-1.5.20.jar (version 1.5)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
174 actionable tasks: 2 executed, 172 up-to-date
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
e: D:\RIYAS\I2GLOABAL\build\new\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.kt: (11, 22): Unresolved reference: common
e: D:\RIYAS\I2GLOABAL\build\new\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.kt: (17, 47): Unresolved reference: GestureHandlerStateManager
e: D:\RIYAS\I2GLOABAL\build\new\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerModule.kt: (400, 3): 'setGestureHandlerState' overrides nothing
 @bortolilucas  @sanjaymistry84

**Comment by sanjaymistry84** [comment]
> I Have changed the version as per your reply but still not working all buttons
> 
> See Below Error: JitsiMeetSDK: [features/app] Error(TypeError){"message":"l.playTouchSound is not a function. facing this issue on clciking these buttons
> 
> Please check your end and let me know how it will resolve.
> 
> See below my packag.json
> 
> { "name": "myapp", "version": "0.0.1", "private": true, "scripts": { "android": "react-native run-android", "ios": "react-native run-ios", "start": "react-native start", "test": "jest", "lint": "eslint ." }, "dependencies": { "@bortolilucas/react-native-jitsimeet": "^2.1.1", "@fullcalendar/daygrid": "^5.10.1", "@fullcalendar/react": "^5.10.1", "@ptomasroos/react-native-multi-slider": "^2.2.2", "@react-native-async-storage/async-storage": "^1.15.9", "@react-native-community/clipboard": "^1.5.1", "@react-native-community/progress-bar-android": "^1.0.4", "@react-native-community/progress-view": "^1.3.1", "@react-native-community/push-notification-ios": "^1.10.1", "@react-native-community/toolbar-android": "^0.2.1", "@react-native-firebase/app": "^14.2.2", "@react-navigation/bottom-tabs": "^6.0.5", "@react-navigation/drawer": "^6.1.3", "@react-navigation/material-top-tabs": "^5.3.19", "@react-navigation/native": "^6.0.2", "@react-navigation/native-stack": "^6.1.0", "@react-navigation/stack": "^6.2.1", "@reduxjs/toolkit": "^1.7.1", "@twotalltotems/react-native-otp-input": "^1.3.11", "axios": "^0.21.1", "formik": "^2.2.9", "lodash.filter": "^4.6.0", "moment": "^2.29.1", "react": "16.13.1", "react-big-calendar": "^0.38.2", "react-data-table-component": "^7.0.2", "react-native": "0.66.0", "react-native-animatable": "^1.3.3", "react-native-blob-util": "^0.13.18", "react-native-calendar-picker": "^7.1.2", "react-native-camera": "^4.1.1", "react-native-circular-progress": "^1.3.7", "react-native-collapsible": "^1.6.0", "react-native-collapsible-tab-view": "^4.4.0", "react-native-date-picker": "^4.1.3", "react-native-dropdown-picker": "^5.1.23", "react-native-gesture-handler": "^2.3.2", "react-native-gifted-chat": "^0.16.3", "react-native-image-pan-zoom": "^2.1.12", "react-native-image-picker": "^4.0.6", "react-native-image-view": "^2.1.9", "react-native-looped-carousel": "0.1.13", "react-native-maps": "0.30.1", "react-native-maps-directions": "^1.8.0", "react-native-media-controls": "^2.3.0", "react-native-pager-view": "^5.4.1", "react-native-paper": "^4.9.2", "react-native-pdf": "^6.3.0", "react-native-popup-menu": "^0.15.11", "react-native-pose": "^0.9.1", "react-native-progress-bar-classic": "^1.2.1", "react-native-push-notification": "^8.1.1", "react-native-ratings": "^8.1.0", "react-native-razorpay": "^2.2.8", "react-native-reanimated": "^2.2.4", "react-native-safe-area-context": "^3.3.2", "react-native-screens": "^3.6.0", "react-native-select-multiple": "^2.1.0", "react-native-slider": "^0.11.0", "react-native-snap-carousel": "^3.9.1", "react-native-splash-screen": "^3.3.0", "react-native-svg": "^12.1.1", "react-native-tab-view": "^2.16.0", "react-native-table-component": "^1.2.1", "react-native-tag-input": "^0.0.21", "react-native-textinput-material-autocomplete": "^1.0.6", "react-native-textinput-with-icons": "^1.0.18", "react-native-toast-message": "^1.4.9", "react-native-vector-icons": "^6.7.0", "react-native-video": "^5.2.0", "react-redux": "^7.2.2", "redux": "^4.0.5", "redux-logger": "^3.0.6", "rn-fetch-blob": "^0.12.0", "yup": "^0.32.11" }, "devDependencies": { "@babel/core": "7.12.9", "@babel/runtime": "7.12.5", "@react-native-community/eslint-config": "2.0.0", "babel-jest": "^26.6.3", "eslint": "7.14.0", "jest": "26.6.3", "metro-react-native-babel-preset": "^0.66.2", "react-native-codegen": "0.0.7", "react-test-renderer": "16.13.1" }, "jest": { "preset": "react-native" } }

**_

> @bortolilucas Can you please reply me on this query.... I am waiting for your reply...

_**

**Comment by bortolilucas** [comment]
Sorry @sanjaymistry84 @riyas145 but I don´t know what might be happening. I'll keep it posted if I find something helpful

**Comment by aaryavrate** [comment]
Is there any solution? The app crashes in release mode.
